// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `OAuth.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.openapi.oauth;

public class OAuthException extends Ice.UserException
{
    public OAuthException()
    {
    }

    public OAuthException(Throwable __cause)
    {
        super(__cause);
    }

    public OAuthException(int code)
    {
        this.code = code;
    }

    public OAuthException(int code, Throwable __cause)
    {
        super(__cause);
        this.code = code;
    }

    public String
    ice_name()
    {
        return "oauth::OAuthException";
    }

    public int code;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::oauth::OAuthException", -1, true);
        __os.writeInt(code);
        __os.endWriteSlice();
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        code = __is.readInt();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = 1229348982L;
}
