// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `OAuth.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.yonyou.openapi.oauth;

public interface OAuthServicePrx extends Ice.ObjectPrx
{
    public OAuthToken authorize(OAuthUrl url)
        throws OAuthException;

    public OAuthToken authorize(OAuthUrl url, java.util.Map<String, String> __ctx)
        throws OAuthException;

    public Ice.AsyncResult begin_authorize(OAuthUrl url);

    public Ice.AsyncResult begin_authorize(OAuthUrl url, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_authorize(OAuthUrl url, Ice.Callback __cb);

    public Ice.AsyncResult begin_authorize(OAuthUrl url, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_authorize(OAuthUrl url, Callback_OAuthService_authorize __cb);

    public Ice.AsyncResult begin_authorize(OAuthUrl url, java.util.Map<String, String> __ctx, Callback_OAuthService_authorize __cb);

    public Ice.AsyncResult begin_authorize(OAuthUrl url,
                                           IceInternal.Functional_GenericCallback1<OAuthToken> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_authorize(OAuthUrl url,
                                           IceInternal.Functional_GenericCallback1<OAuthToken> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_authorize(OAuthUrl url,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<OAuthToken> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_authorize(OAuthUrl url,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<OAuthToken> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public OAuthToken end_authorize(Ice.AsyncResult __result)
        throws OAuthException;

    public void validateToken(String accessToken)
        throws OAuthException;

    public void validateToken(String accessToken, java.util.Map<String, String> __ctx)
        throws OAuthException;

    public Ice.AsyncResult begin_validateToken(String accessToken);

    public Ice.AsyncResult begin_validateToken(String accessToken, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_validateToken(String accessToken, Ice.Callback __cb);

    public Ice.AsyncResult begin_validateToken(String accessToken, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_validateToken(String accessToken, Callback_OAuthService_validateToken __cb);

    public Ice.AsyncResult begin_validateToken(String accessToken, java.util.Map<String, String> __ctx, Callback_OAuthService_validateToken __cb);

    public Ice.AsyncResult begin_validateToken(String accessToken,
                                               IceInternal.Functional_VoidCallback __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_validateToken(String accessToken,
                                               IceInternal.Functional_VoidCallback __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_validateToken(String accessToken,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_VoidCallback __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_validateToken(String accessToken,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_VoidCallback __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public void end_validateToken(Ice.AsyncResult __result)
        throws OAuthException;

    public String createCode(OAuthUrl url)
        throws OAuthException;

    public String createCode(OAuthUrl url, java.util.Map<String, String> __ctx)
        throws OAuthException;

    public Ice.AsyncResult begin_createCode(OAuthUrl url);

    public Ice.AsyncResult begin_createCode(OAuthUrl url, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_createCode(OAuthUrl url, Ice.Callback __cb);

    public Ice.AsyncResult begin_createCode(OAuthUrl url, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_createCode(OAuthUrl url, Callback_OAuthService_createCode __cb);

    public Ice.AsyncResult begin_createCode(OAuthUrl url, java.util.Map<String, String> __ctx, Callback_OAuthService_createCode __cb);

    public Ice.AsyncResult begin_createCode(OAuthUrl url,
                                            IceInternal.Functional_GenericCallback1<String> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createCode(OAuthUrl url,
                                            IceInternal.Functional_GenericCallback1<String> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_createCode(OAuthUrl url,
                                            java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<String> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createCode(OAuthUrl url,
                                            java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<String> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public String end_createCode(Ice.AsyncResult __result)
        throws OAuthException;
}
